version: '3.9'
services:


  lara-postgres:
    image: postgres:16.2-alpine3.19
    volumes:
      - lara-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: lara
      POSTGRES_PASSWORD: lara
      POSTGRES_DB: lara
    ports:
      - "54321:5432"

  rabbitmq:
      image: rabbitmq:3.13.1-management-alpine
      ports:
          - "15672:15672"
          - "5672:5672"
      volumes:
          - rabbitmq:/var/lib/rabbitmq

volumes:
    lara-postgres:
    rabbitmq:
